"""empty message

Revision ID: 8da7602667cd
Revises: 94fcbde5c56e
Create Date: 2022-05-31 21:04:10.295408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8da7602667cd'
down_revision = '94fcbde5c56e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('image', sa.String(), nullable=True))
    op.drop_constraint('castings_movie_id_fkey', 'castings', type_='foreignkey')
    op.drop_constraint('castings_actor_id_fkey', 'castings', type_='foreignkey')
    op.create_foreign_key(None, 'castings', 'movies', ['movie_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'castings', 'actors', ['actor_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('movies', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'image')
    op.drop_constraint(None, 'castings', type_='foreignkey')
    op.drop_constraint(None, 'castings', type_='foreignkey')
    op.create_foreign_key('castings_actor_id_fkey', 'castings', 'actors', ['actor_id'], ['id'])
    op.create_foreign_key('castings_movie_id_fkey', 'castings', 'movies', ['movie_id'], ['id'])
    op.drop_column('actors', 'image')
    # ### end Alembic commands ###
